spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: <your-root-password>

  # JPA settings
  jpa:
    hibernate:
      ddl-auto: update
